train:
  device: cuda
  epochs: 50
  batch_size: 2
  learning_rate: 5.0e-5
  mixed_precision: false
  gradient_clip_norm: 1.0
  num_workers: 24
  pin_memory: true
  dataloader_prefetch_factor: 4
  dataloader_persistent_workers: true
  enable_cuda_prefetch: true
  allow_tf32: true
  
  train_data_path: /DATA/ANIME/data  # TODO: 请修改为您实际的动漫数据集路径
  val_data_path: /DATA/ANIME/vali    # TODO: 请修改为您实际的验证集路径
  val_every: 1
  log_every: 100
  early_stopping_patience: 15
  checkpoint_dir: ./models/checkpoints/anime_finetune
  auto_resume: false
  torch_compile: false

loss_global_scale: 1.0

loss_weights:
  pixel: 1.0
  frequency: 0.2
  perceptual: 1.0
  vgg: 0.0
  adversarial: 0.05  # 微调时开启轻微对抗

loss_options:
  enable_anime_loss: true # 开启针对动漫的Loss特性

gan:
  enabled: true
  discriminator_lr: 5.0e-5
  disc_update_ratio: 1

save_metrics:
  psnr: true
  ssim: true
  lpips: true
  val_loss : false

online_data_options:
  crop_size: 128
  scale: 2
  downsample_filters: [nearest, bilinear, bicubic, lanczos]
  noise_p: 0.1         # 动漫源通常比较干净，减少噪声增强
  noise_std_min: 0.001
  noise_std_max: 0.01
  blur_p: 0.1
  blur_sigma_min: 0.4
  blur_sigma_max: 1.0
  jpeg_p: 0.3          # 增加抗压缩能力
  jpeg_quality_min: 40 # 动漫源常见压缩
  jpeg_quality_max: 95
  webp_p: 0.3
  webp_quality_min: 40
  webp_quality_max: 95


model_config:
  image_size: 64
  in_channels: 3
  image_range: 1.0
  use_tiling: False
  tile_size: 64
  tile_pad: 32
  # MambaIRv2 SR2-L settings
  upscale: 2
  embed_dim: 174
  d_state: 16
  depths: [6, 6, 6, 6, 6, 6, 6, 6, 6]
  num_heads: [6, 6, 6, 6, 6, 6, 6, 6, 6]
  window_size: 16
  inner_rank: 64
  num_tokens: 128
  convffn_kernel_size: 5
  mlp_ratio: 2.0
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
