train:
  device: cuda
  epochs: 500
  batch_size: 3
  learning_rate: 5.0e-5
  mixed_precision: false
  gradient_clip_norm: 1.0
  num_workers: 24
  pin_memory: true
  dataloader_prefetch_factor: 4
  dataloader_persistent_workers: true
  enable_cuda_prefetch: true
  allow_tf32: true
  
  train_data_path: /DATA/anime/train  # TODO: 请修改为您实际的动漫数据集路径
  val_data_path: /DATA/anime/test    # TODO: 请修改为您实际的验证集路径
  val_every: 1
  log_every: 100
  early_stopping_patience: 50
  checkpoint_dir: ./models/checkpoints/anime_finetune
  auto_resume: false
  torch_compile: false

loss_global_scale: 1.0

loss_weights:
  pixel: 1.2
  frequency: 0.2
  perceptual: 0.05
  vgg: 0.0
  adversarial: 0.05  # 微调时开启轻微对抗

loss_options:
  enable_anime_loss: true # 开启针对动漫的Loss特性

gan:
  enabled: true
  discriminator_lr: 5.0e-5
  disc_update_ratio: 1

save_metrics:
  psnr: false
  ssim: false
  lpips: true
  val_loss : true

online_data_options:
  crop_size: 128
  scale: 2
  downsample_filters: [nearest, bilinear, bicubic, lanczos]
  noise_p: 0.0         # 根据要求，不对图片做加噪
  noise_std_min: 0.001
  noise_std_max: 0.01
  blur_p: 0.0          # 同样关闭模糊以获得更干净的下采样
  blur_sigma_min: 0.4
  blur_sigma_max: 1.0
  jpeg_p: 0.0          # 关闭 JPEG 压缩噪声
  jpeg_quality_min: 40
  jpeg_quality_max: 95
  webp_p: 0.0          # 关闭 WebP 压缩噪声
  webp_quality_min: 40
  webp_quality_max: 95


model_config:
  image_size: 64
  in_channels: 3
  image_range: 1.0
  hat_patch_size: 1
  hat_body_hid_channels: 180
  hat_upsampler_hid_channels: 64
  hat_depths: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  hat_num_heads: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  hat_window_size: 16
  hat_compress_ratio: 3
  hat_squeeze_factor: 30
  hat_conv_scale: 0.01
  hat_overlap_ratio: 0.5
  hat_mlp_ratio: 2.0
  hat_qkv_bias: True
  hat_drop_rate: 0.0
  hat_attn_drop_rate: 0.0
  hat_drop_path_rate: 0.1
  hat_norm_layer: 'nn.LayerNorm'
  hat_patch_norm: true
  hat_use_checkpoint: true
  hat_resi_connection: '1conv'
